### 
GET http://localhost:3000/books
###
GET http://localhost:3000/books/3
###
GET http://localhost:3000/books/7
###

POST http://localhost:3000/books
Content-Type: application/json

{
  "title": "Rayuela",
  "author": "Julio Cortazar",
  "rating": 1
}

###
PUT http://localhost:3000/books/1
Content-Type: application/json

{
  "title": "Rayuela",
  "author": "Julio Cortazar",
  "rating": 2
}
###
DELETE http://localhost:3000/books/4